### ISSUE TITLE
Le texte de la cover se superpose au bouton "en savoir plus"

### ISSUE THREAD

**Issue by DuaelFr** [insoumis-local/wordpress-template-legislatives#11]
Le texte de la cover est centré à cause de l'alignement flex et se superpose donc facilement avec le bouton en savoir plus.
Réaligner ce texte en haut et voir comment on pourrait faire en sorte que même avec une liste de villes énorme il n'y ait pas chevauchement.

**Comment by nicooprat** [comment]
un site en exemple ? ça devrait justement s'adapter, ne pas se chevaucher et la page devrait dépasser 100% si trop de texte ou écran trop petit... A moins que certains hauteurs soient fixées ?

**Comment by DuaelFr** [comment]
En fait il ne faut pas que ça s'agrandisse sinon le bouton en savoir plus sort de l'écran et on perd beaucoup trop en ergonomie et en design (le bas de la photo va être moche car la découpe diagonale s'adaptera pas en hauteur).
Je crois que tu as fait une modif en ce sens (height => min-height) qu'il faudrait revert d'ailleurs

**Comment by nicooprat** [comment]
Oui effectivement il faut faire en sorte que il n'y ait pas trop de texte, mais précédemment ce texte était tronqué, donc par défaut mieux vaut que ce soit moche mais accessible/lisible ^^

Donc je vote pour conserver `min-height` mais inciter les auteurs à mettre moins de contenus ou sauter moins de lignes... (cf https://github.com/insoumis-local/wordpress-template-legislatives/issues/12).

Ou alors la zone de texte devient "scrollable" en cas d'overflow du contenu, mais + chiant à gérer. Et le but n'est pas d'avoir trop de texte de toute façon...
