### ISSUE TITLE
Mettre une hauteur max d'image dans l'affichage de la page Blog

### ISSUE THREAD

**Issue by DaSchtroumpf** [insoumis-local/wordpress-template-legislatives#15]
Ceci pour éviter que les images se superposent avec la boîte du dessus. Mettre un paramètre de hauteur max (avec recadrage plutôt que déformation) des images affichées. 

![image](https://cloud.githubusercontent.com/assets/26440361/26099431/f69ebae4-3a2a-11e7-96e4-e1b373f276a2.png)

**Comment by nicooprat** [comment]
Quel OS / navigateur ?

Je n'ai pas ce pb chez moi : http://multi-insoumis.bluefairy.fr/69-3/actualites/

Je pense que c'est un souci de javascript et que limiter les dimensions des images ne réglera pas le pb.

**Comment by DaSchtroumpf** [comment]
En effet, le souci a disparu. Mais régulièrement il réapparaît, même sans images...
