### ISSUE TITLE
Disparition des boutons de partage...

### ISSUE THREAD

**Issue by Damien24-4** [insoumis-local/wordpress-template-legislatives#16]
... au niveau de l'apperçu des articles : http://www.domaine-test.historius.fr/actualites/

**Comment by DuaelFr** [comment]
Je ne comprends pas. Sur la page que tu cites c'est normal qu'il n'y ait pas de boutons de partage puisque c'est une liste des posts et pas un post tout seul.

**Comment by Damien24-4** [comment]
Il me semble qu'on avait tout meme mis de quoi partager à cet endroit.

**Comment by DuaelFr** [comment]
Les boutons de partage viennent d'un plugin, pas du thème.
Les seuls trucs liés aux réseaux sociaux dans le thème sont les liens vers twitter, facebook et youtube que tu peux activer dans le footer.

**Comment by Damien24-4** [comment]
Oui mais du coup il avait été ajoutés par Da_Schtroumpf et y a une maj qui les a fait sauter.

**Comment by Damien24-4** [comment]
Le truc a du sauter dans le wp directement oui.

**Comment by DuaelFr** [comment]
Je pense que tu fais erreur. Le plugin est bien présent et fonctionne. Mais il n'est actif que sur les pages de contenu (ex. http://www.domaine-test.historius.fr/2017/05/09/bonjour-tout-le-monde/)
La page que tu cites plus haut est une page de liste. Ça n'a pas vraiment de sens de la partager.

**Comment by Damien24-4** [comment]
Da_Schtroumpf avait réussi à mettre les logo sur les apperçus des articles justement.

**Comment by DuaelFr** [comment]
Vu qu'il n'est pas intervenu sur le thème, je vois mal comment il a fait ça et comment le thème pourrait en être responsable. Je propose d'attendre son retour et de lui demande :)

**Comment by Damien24-4** [comment]
On arrive pas à se comprendre xD
C'est pas sur le thème directement on est d'accord ;-)

**Comment by DaSchtroumpf** [comment]
A un moment donné, les boutons de partage fonctionnaient sur la liste des articles en effet. Sans toucher au theme, je crois. A moins que je n'y aie touché? J'ai un doute, mais je pense pas. 

BRef, on avait à un moment donné des boutons de partage directement sur les excerpt des billets de blog. Dual avait même trouvé ça ultra moche. 

A bien y réfléchir, j'avoue que ça n'a pas trop de sens. Que chaque page puisse être partagée, ok. Idem pour chaque article individuel. Pour l'extrait en page d'actu, ça n'a pas trop de sens finalement :/. On partage après avoir lu ^^

**Comment by Damien24-4** [comment]
Et j'avais répondu que beaucoup partageait les articles sur un titre, un extrait. Pour l'équipe de campagne ça peut etre pratique ou toutes les personnes autour aussi. Mais bon je vais pas en faire tout un fromage si vous etes pas chaud.

Si y a que moi qui demande on peut fermer l'issu sans soucis ;)
