### ISSUE TITLE
Corriger le style du template Accueil

### ISSUE THREAD

**Issue by DuaelFr** [insoumis-local/wordpress-template-legislatives#8]
Suite aux dernières modifications de la cover principale, ce template ne s'affiche plus comme prévu.
L'image est en contain et plus en cover, l'ensemble est collé à gauche sur 50% de la largeur de l'écran environ.

**Comment by nicooprat** [comment]
Normalement :

* logo par défaut -> background centré en contain avec un faux padding (directement via SVG viewbox), le + simple : https://github.com/insoumis-local/wordpress-template-legislatives/blob/master/assets/styles/components/_cover.scss#L12
* photo -> background centré en cover : https://github.com/insoumis-local/wordpress-template-legislatives/blob/master/lib/customizer.php#L155 

Un exemple d'un site où y'a le pb ?
